# In Types.tsx
SETTING_APP_NAME = "app_name"
SETTING_CONTACT_EMAIL = "app_contact_email"
SETTING_CREATOR = "app_creator"
SETTING_MASTER_USER = "readonly_master_user_email"
SETTING_URL = "readonly_master_url"
SETTING_MENTOR_PASSWORD = "mentor_password_key"
SETTING_GITHUB_CLIENT_ID = "github_client_id"
SETTING_GITHUB_CLIENT_SECRET = "github_client_secret"
SETTING_QUEUE_ON = "queue_status"
SETTING_OFFICIAL_MESSAGE = "queue_message"
SETTING_JITSI_LINK = "jitsi_link"

SETTINGS_ENV_PERMENANT = [SETTING_MASTER_USER, SETTING_URL]
SETTINGS_PUBLIC = [
    SETTING_APP_NAME,
    SETTING_CONTACT_EMAIL,
    SETTING_CREATOR,
    SETTING_QUEUE_ON,
    SETTING_OFFICIAL_MESSAGE,
    SETTING_URL,
    SETTING_JITSI_LINK,
    SETTING_GITHUB_CLIENT_ID
]

ALLDEFAULTSETTINGS = [
    SETTING_APP_NAME,
    SETTING_CONTACT_EMAIL,
    SETTING_JITSI_LINK,
    SETTING_CREATOR,
    SETTING_MENTOR_PASSWORD,
    SETTING_GITHUB_CLIENT_SECRET
]
