"""empty message

Revision ID: 4408c3611fae
Revises: fdafd4c51ead
Create Date: 2021-09-14 03:57:36.637802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4408c3611fae'
down_revision = 'fdafd4c51ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'jitsi_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('jitsi_uuid', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
