"""empty message

Revision ID: 653093fddc44
Revises: 8d950e758485
Create Date: 2020-08-28 18:15:33.543244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653093fddc44'
down_revision = '8d950e758485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('uid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'uid')
    # ### end Alembic commands ###
