"""empty message

Revision ID: 68d234e0f83e
Revises: a9fd5b5f5b0a
Create Date: 2019-12-21 07:11:51.818491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d234e0f83e'
down_revision = 'a9fd5b5f5b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'rating')
    # ### end Alembic commands ###
