"""empty message

Revision ID: 8d950e758485
Revises: de3ab01f4eb0
Create Date: 2020-01-23 12:05:29.835861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d950e758485'
down_revision = 'de3ab01f4eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_last_signin', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_last_signin')
    # ### end Alembic commands ###
