"""empty message

Revision ID: a9fd5b5f5b0a
Revises: 8a8e177c22c8
Create Date: 2019-12-16 17:05:04.697429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fd5b5f5b0a'
down_revision = '8a8e177c22c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('affiliation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'affiliation')
    # ### end Alembic commands ###
