"""empty message

Revision ID: de3ab01f4eb0
Revises: 68d234e0f83e
Create Date: 2020-01-09 13:56:48.972103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3ab01f4eb0'
down_revision = '68d234e0f83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'clients', ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    # ### end Alembic commands ###
