"""empty message

Revision ID: fdafd4c51ead
Revises: 653093fddc44
Create Date: 2021-09-14 03:10:13.521278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdafd4c51ead'
down_revision = '653093fddc44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('claim_location', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('jitsi_uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'jitsi_uuid')
    op.drop_column('tickets', 'claim_location')
    # ### end Alembic commands ###
